export const defaultColors = {
    header:              '#82A062',
    background:          '#09090b',
    panels:              '#18181b',
    group:               '#27272a',
    buttons:             '#09090b',
    buttonsHover:          '#5b5b5e',
    buttonsText:          '#ffffff',
    buttonsPressed:      '#5b5b5e',
    
    audioButton:         '#3b82f6', 
    audioButtonHover:   '#60a5fa',
    audioButtonPressed:  '#60a5fa',
    
    keyButtons:          '#f4f4f5', 
    keyText:             '#09090b', 
    text:                '#fafafa', 
    cursor:              '#3b82f6',
    progress:            '#ffffff',
    waveform:            '#52525b', 
    cream:               '#18181b',
    
    // Bounding Box Styles
    box:                 '#82A062',
    boxSelected:         '#FFFFFF',
    boxFill:             'rgba(16, 185, 129, 0.05)',
    boxFillSelected:     'rgba(52, 211, 153, 0.15)',
    boxLabel:            '#ffffff',
    boxLabelBg:          '#82A062',
    
    textInput:           '#18181b',
    textInputText:       '#fafafa',
    placeholderText:     '#52525b',
};

export const frogThemeColors = {
    header: '#1E1E1E',
    background:          '#E6E5C9',
    panels:              '#82A062',
    group:               '#C8D9A3',
    buttons:             '#FEECBE',
    buttonsHover:          '#FFDE9E',
    buttonsText:        '#1E1E1E',
    buttonsPressed:      '#FFDE9E',
    audioButton:         '#CAE4EF',
    audioButtonHover:  '#B4D2EF',
    audioButtonPressed:  '#B4D2EF',
    keyButtons:          '#1E1E1E',
    keyText:             '#E6E5C9',
    text:                '#1E1E1E',
    cursor:              '#CAE4EF',
    progress:            '#F3F3E4',
    waveform:            '#1E1E1E',
    cream:               '#F3F3E4',
    box:                 '#82A062',
    boxSelected:         '#1E1E1E',
    boxFill:             'rgba(130, 160, 98, 0.10)',
    boxFillSelected:     'rgba(30, 30, 30, 0.10)',
    boxLabel:            '#1E1E1E',
    boxLabelBg:          '#C8D9A3',
    textInput: '#FFFFFF',
    textInputText: '#1E1E1E',
     placeholderText:'#1E1E1E',
};