export const defaultColors = {
    background:          '#F9FAFB',
    panels:              '#6B7280',
    group:               '#D1D5DB',
    buttons:             '#E5E7EB',
    buttonsPressed:      '#D1D5DB',
    audioButton:         '#BFDBFE',
    audioButtonPressed:  '#93C5FD',
    keyButtons:          '#1F2937',
    keyText:             '#F9FAFB',
    text:                '#1F2937',
    cursor:              '#3B82F6',
    progress:            '#E5E7EB',
    waveform:            '#1F2937',
    cream:               '#E5E7EB',
    box:                 '#3B82F6',
    boxSelected:         '#1D4ED8',
    boxFill:             'rgba(59, 130, 246, 0.15)',
    boxFillSelected:     'rgba(29, 78, 216, 0.25)',
    boxLabel:            '#1F2937',
    boxLabelBg:          '#BFDBFE',
};

export const frogThemeColors = {
    background:          '#E6E5C9',
    panels:              '#82A062',
    group:               '#C8D9A3',
    buttons:             '#FEECBE',
    buttonsPressed:      '#FFDE9E',
    audioButton:         '#CAE4EF',
    audioButtonPressed:  '#B4D2EF',
    keyButtons:          '#1E1E1E',
    keyText:             '#E6E5C9',
    text:                '#1E1E1E',
    cursor:              '#CAE4EF',
    progress:            '#F3F3E4',
    waveform:            '#1E1E1E',
    cream:               '#F3F3E4',
    box:                 '#82A062',
    boxSelected:         '#1E1E1E',
    boxFill:             'rgba(130, 160, 98, 0.15)',
    boxFillSelected:     'rgba(30, 30, 30, 0.25)',
    boxLabel:            '#1E1E1E',
    boxLabelBg:          '#C8D9A3',
};